Updated Google Calendar call
ActoKids/web-crawler pull request #8
Opened 2019-02-06 23:15 UTC by rberry206

Added more fields and some exceptions

2019-02-09 23:11 UTC, MikeJLeon approved these changes

2019-02-09 23:22 UTC, MikeJLeon requested changes
merging into wrong branch

2019-02-09 23:41 UTC, MikeJLeon approved these changes

2019-02-10 00:42 UTC, mrvirus9898 approved these changes

2019-02-10 04:18 UTC, merged